### ISSUE TITLE
Crash due to sound being null

### ISSUE THREAD

**Issue by Gaz492** [Frinn38/Custom-Machinery#140]
We have some custom machinery in Stoneblock 4 and we have some users running into an issue where the game crashes due to an issue with sound being null I have attached the crash report below, if you need more info do let me know.

Crash report https://pste.me/@DBLIuY0qE_Q

**Comment by Frinn38** [comment]
That's a weird issue, the crash report is very useful and show precisely where the issue is, but I'm not sure what's causing it.

Can you tell me when these crashes happen ? Is it totally random or simply reproduceable, like just placing a specific machine or running a specific recipe ?

In all cases I implemented a fix which should resolve this issue for the next update but I can't be 100% without knowing what causes it.

**Comment by Gaz492** [comment]
Unfortunately, I believe it's just a random occurrence, the report we had on our issue tracker only mentioned getting this while joining their world and after a few attempts they were able to load in fine.

https://github.com/FTBTeam/FTB-Modpack-Issues/issues/9338

**Comment by Gaz492** [comment]
We had someone else make an issue for the same crash, but they mentioned that its happening when they try crafting something, then once they join their world after the crash its fine again until they do more crafting in the block.

https://github.com/FTBTeam/FTB-Modpack-Issues/issues/9389#issuecomment-3476281244

**Comment by Frinn38** [comment]
The new update (0.10.49) is released and should fix that issue.

**Comment by robabrams** [comment]
We are using the new version 0.10.49 and this is still actively occurring. It crashes every time I try to craft something. Both in the circuit fabricator and World Engine. I have tried turning all sounds off - this does not help. I have even tried activating the machine remotely (via ender chests) - it still crashes. Let me know if you need a more current crash log.
https://pste.me/@0fnZBFjpCxw

**Comment by Saereth** [comment]
We are still seeing other people crashing from this bug as of the latest version, I've included another crashlog here from yesterday:
https://github.com/user-attachments/files/23641447/crash-2025-11-19_23.42.13-client.txt

if it helps, here is the machine json that is crashing:
world_engine.json

```
{
  "name": {
    "text": "ftb.machine.world_engine"
  },
  "appearance": {
    "running": {
      "custommachinery:ambient_sound": {
        "sound": "draconicevolution:core_sound",
        "volume": 2.27,
        "pitch": 0.18
      },
      "custommachinery:block": "ftb:machine/world_engine_active",
      "custommachinery:light": 15
    },
    "errored": {
      "custommachinery:block": "ftb:machine/world_engine_errored",
      "custommachinery:light": 6
    },
    "paused": {
      "custommachinery:block": "ftb:machine/world_engine_paused",
      "custommachinery:light": 7
    },
    "custommachinery:block": "ftb:machine/world_engine",
    "custommachinery:color": 468512,
    "custommachinery:hardness": -1.0,
    "custommachinery:keep_inventory": true,
    "custommachinery:mining_level": "minecraft:needs_diamond_tool",
    "custommachinery:resistance": 2000.0
  },
  "components": [
    {
      "type": "custommachinery:contraption",
      "stress_impact": 0.0,
      "config": {
        "TOP": "DISABLED",
        "BOTTOM": "ENABLED",
        "FRONT": "DISABLED",
        "RIGHT": "DISABLED",
        "BACK": "DISABLED",
        "LEFT": "DISABLED"
      }
    },
    {
      "type": "custommachinery:energy",
      "max_output": 0,
      "config": {
        "TOP": "INPUT",
        "BOTTOM": "INPUT",
        "FRONT": "INPUT",
        "RIGHT": "INPUT",
        "BACK": "INPUT",
        "LEFT": "INPUT",
        "input": true
      },
      "capacity": 250000
    },
    {
      "type": "custommachinery:fluid",
      "mode": "input",
      "unique": true,
      "id": "fluid_input_1",
      "capacity": 10000
    },
    {
      "type": "custommachinery:fluid",
      "mode": "input",
      "config": {
        "TOP": "BOTH",
        "BOTTOM": "BOTH",
        "FRONT": "BOTH",
        "RIGHT": "BOTH",
        "BACK": "BOTH",
        "LEFT": "BOTH"
      },
      "unique": true,
      "id": "fluid_input_2",
      "capacity": 10000
    },
    {
      "type": "custommachinery:heat",
      "insulation": 1000.0,
      "config": {
        "TOP": "ENABLED",
        "BOTTOM": "ENABLED",
        "FRONT": "ENABLED",
        "RIGHT": "ENABLED",
        "BACK": "ENABLED",
        "LEFT": "ENABLED"
      },
      "capacity": 10000.0
    },
    {
      "type": "custommachinery:item",
      "id": "item_input_1",
      "mode": "input"
    },
    {
      "type": "custommachinery:item",
      "id": "item_input_2",
      "mode": "input"
    },
    {
      "type": "custommachinery:item",
      "id": "item_input_3",
      "mode": "input"
    },
    {
      "type": "custommachinery:item",
      "id": "item_input_4",
      "mode": "input"
    },
    {
      "type": "custommachinery:item",
      "id": "item_input_5",
      "mode": "input"
    },
    {
      "type": "custommachinery:item",
      "id": "item_input_6",
      "mode": "input"
    },
    {
      "type": "custommachinery:item",
      "id": "output_item_1",
      "mode": "output"
    },
    {
      "type": "custommachinery:item",
      "id": "output_item_2",
      "mode": "output"
    },
    {
      "type": "custommachinery:item",
      "id": "output_item_3",
      "mode": "output"
    },
    {
      "type": "custommachinery:item",
      "id": "output_item_4",
      "mode": "output"
    },
    {
      "type": "custommachinery:item",
      "id": "output_item_5",
      "mode": "output"
    },
    {
      "type": "custommachinery:item",
      "id": "output_item_6",
      "mode": "output"
    },
    {
      "type": "custommachinery:source",
      "capacity": 100000,
      "max_input": 10000,
      "max_output": 0
    }
  ],
  "gui": [
    {
      "type": "custommachinery:background",
      "texture": {
        "texture": "ftb:textures/gui/base_background.png"
      },
      "width": 192,
      "height": 192
    },
    {
      "type": "custommachinery:config",
      "texture_hovered": {
        "texture": "ftb:textures/gui/base_config_hovered.png"
      },
      "texture": {
        "texture": "ftb:textures/gui/base_config.png"
      },
      "x": 107,
      "y": 51,
      "width": 18,
      "height": 18
    },
    {
      "type": "custommachinery:dump",
      "x": 36,
      "y": 18,
      "width": 16,
      "height": 7,
      "tanks": "fluid_input_1"
    },
    {
      "type": "custommachinery:dump",
      "x": 61,
      "y": 18,
      "width": 16,
      "height": 7,
      "tanks": "fluid_input_2"
    },
    {
      "type": "custommachinery:energy",
      "texture_filled": {
        "texture": "ftb:textures/gui/base_energy_storage_filled.png"
      },
      "x": 8,
      "y": 9,
      "width": 7,
      "height": 80,
      "texture_empty": {
        "texture": "ftb:textures/gui/base_energy_storage_empty.png"
      }
    },
    {
      "type": "custommachinery:fluid",
      "id": "fluid_input_1",
      "texture": {
        "texture": "ftb:textures/gui/base_fluid_storage.png"
      },
      "x": 35,
      "y": 26,
      "width": 18,
      "height": 44
    },
    {
      "type": "custommachinery:fluid",
      "id": "fluid_input_2",
      "texture": {
        "texture": "ftb:textures/gui/base_fluid_storage.png"
      },
      "x": 60,
      "y": 26,
      "width": 18,
      "height": 44
    },
    {
      "type": "custommachinery:heat",
      "x": 23,
      "y": 18,
      "width": 7,
      "height": 52,
      "texture_empty": {
        "texture": "ftb:textures/gui/base_heat_storage.png"
      },
      "texture_filled": {
        "texture": "ftb:textures/gui/base_heat_storage_filled.png"
      }
    },
    {
      "type": "custommachinery:player_inventory",
      "texture": {
        "texture": "ftb:textures/gui/base_inventory.png"
      },
      "x": 15,
      "y": 107,
      "width": 162,
      "height": 76
    },
    {
      "type": "custommachinery:progress",
      "orientation": "BOTTOM",
      "x": 150,
      "y": 40,
      "width": 16,
      "height": 24,
      "texture_empty": {
        "texture": "ftb:textures/gui/base_progress_empty.png"
      },
      "texture_filled": {
        "texture": "ftb:textures/gui/base_progress_filled.png"
      }
    },
    {
      "type": "custommachinery:slot",
      "id": "item_input_1",
      "texture": {
        "texture": "ftb:textures/gui/base_slot.png"
      },
      "x": 130,
      "y": 5,
      "width": 18,
      "height": 18
    },
    {
      "type": "custommachinery:slot",
      "id": "item_input_2",
      "texture": {
        "texture": "ftb:textures/gui/base_slot.png"
      },
      "x": 149,
      "y": 5,
      "width": 18,
      "height": 18
    },
    {
      "type": "custommachinery:slot",
      "id": "item_input_3",
      "texture": {
        "texture": "ftb:textures/gui/base_slot.png"
      },
      "x": 168,
      "y": 5,
      "width": 18,
      "height": 18
    },
    {
      "type": "custommachinery:slot",
      "id": "item_input_4",
      "texture": {
        "texture": "ftb:textures/gui/base_slot.png"
      },
      "x": 130,
      "y": 24,
      "width": 18,
      "height": 18
    },
    {
      "type": "custommachinery:slot",
      "id": "item_input_5",
      "texture": {
        "texture": "ftb:textures/gui/base_slot.png"
      },
      "x": 149,
      "y": 24,
      "width": 18,
      "height": 18
    },
    {
      "type": "custommachinery:slot",
      "id": "item_input_6",
      "texture": {
        "texture": "ftb:textures/gui/base_slot.png"
      },
      "x": 168,
      "y": 24,
      "width": 18,
      "height": 18
    },
    {
      "type": "custommachinery:slot",
      "id": "output_item_1",
      "texture": {
        "texture": "ftb:textures/gui/base_slot.png"
      },
      "x": 130,
      "y": 62,
      "width": 18,
      "height": 18
    },
    {
      "type": "custommachinery:slot",
      "id": "output_item_2",
      "texture": {
        "texture": "ftb:textures/gui/base_slot.png"
      },
      "x": 149,
      "y": 62,
      "width": 18,
      "height": 18
    },
    {
      "type": "custommachinery:slot",
      "id": "output_item_3",
      "texture": {
        "texture": "ftb:textures/gui/base_slot.png"
      },
      "x": 168,
      "y": 62,
      "width": 18,
      "height": 18
    },
    {
      "type": "custommachinery:slot",
      "id": "output_item_4",
      "texture": {
        "texture": "ftb:textures/gui/base_slot.png"
      },
      "x": 130,
      "y": 81,
      "width": 18,
      "height": 18
    },
    {
      "type": "custommachinery:slot",
      "id": "output_item_5",
      "texture": {
        "texture": "ftb:textures/gui/base_slot.png"
      },
      "x": 149,
      "y": 81,
      "width": 18,
      "height": 18
    },
    {
      "type": "custommachinery:slot",
      "id": "output_item_6",
      "texture": {
        "texture": "ftb:textures/gui/base_slot.png"
      },
      "x": 168,
      "y": 81,
      "width": 18,
      "height": 18
    },
    {
      "type": "custommachinery:source",
      "x": 86,
      "y": 26,
      "width": 18,
      "height": 44
    },
    {
      "type": "custommachinery:status",
      "x": 36,
      "y": 74,
      "width": 16,
      "height": 16
    }
  ],
  "processor": {
    "type": "custommachinery:machine",
    "amount": 16
  }
}
```

**Comment by Frinn38** [comment]
I've released a new version just now that should (hopefully) fix that issue this time.
