### ISSUE TITLE
Outputs to incorrect slot when multiple outputs are used.

### ISSUE THREAD

**Issue by NihilEntropy** [Frinn38/Custom-Machinery#37]
Machine json: https://pastebin.com/wCJwUR9K
Machine Recipe json: https://pastebin.com/McXuMpuS

No errors in custommachine log, other recipes work just fine. The JEI shows it outputing to the wrong slot as-well, even with different names, and switching mode to both, except for the slot which it uses as the input slot, then it goes there. If I blacklist the items in the other slot, the output doesn't appear, and it eats the item.

If I have any typos in the code, I apologize in advanced, but I tried my hardest to find what I did wrong, and I can't.

**Comment by Frinn38** [comment]
Your machines and recipe are fine, there is a bug in the jei integration for the current version.
The bug is already fixed in dev, I just didn't push an update since the fix was made.
Closing as there is already an issue opened for this bug.

**Comment by NihilEntropy** [comment]
> Your machines and recipe are fine, there is a bug in the jei integration for the current version. The bug is already fixed in dev, I just didn't push an update since the fix was made. Closing as there is already an issue opened for this bug.

What version should I expect the fix for this, as it still appears to be present in the latest custommachinery-1.16.5-0.5.6.jar?

**Comment by NihilEntropy** [comment]
I don't think it is the JEI integration, as it mechanically isn't doing what it should. It is as though only one output slot is cared about, and universally prioritized, even when a recipe specifies a different slot.

![image](https://user-images.githubusercontent.com/52515211/152275338-ff69a2bb-8750-4392-a0b5-d4ae6e1be6bf.png)
![image](https://user-images.githubusercontent.com/52515211/152275377-11a1e9fa-7720-47a1-a362-e291a265f584.png)
![image](https://user-images.githubusercontent.com/52515211/152275423-c59477ec-fc01-484b-87a4-d882f74bb89f.png)
![image](https://user-images.githubusercontent.com/52515211/152275493-ca5fd7af-4cbf-481f-a59f-120bad297c30.png)
Notice, two different outputs, one bucketoutslot, the other is outslot. bucketoutslot is specified in recipe for the output, yet outslot is used.
![image](https://user-images.githubusercontent.com/52515211/152275578-00b707df-91d1-4150-ac3b-fc70f7ea5dc9.png)
Further confirmation here, as bucketoutslot is located directly below the bucketslot.

**Comment by Frinn38** [comment]
A ok I misunderstood the issue here. I will do some testing to see why the item recipe requirement doesn't respect the "slot"property.

**Comment by NihilEntropy** [comment]
> A ok I misunderstood the issue here. I will do some testing to see why the item recipe requirement doesn't respect the "slot"property.

Hmm, I just realized this might affect multi-outputs if you have more than one output slots with different names but all usable for an output. Maybe it needs to have a list involved, like "slots" : ["outslot1", "outslot2"] and a slot whitelist bool.

**Comment by Frinn38** [comment]
Fixed in 0.5.8
